---
title: "Analysis of Hardwood Price-Size Data"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    css: jf_style.css
    include:
      before_body: header_white_logo_R.html
---




```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

#### this section loads relevant R libraries, some extra functions and sets the working directory (where files are loaded/saved)####

library(tidyverse) #loads suite of tidyverse libraries
library(knitr)
library(rpivotTable)
library(rmarkdown)
library(yaml)
library(scales)
library(car)
library(emmeans)
library(multcompView)
library(stringi)
library(flexdashboard)
library(plotly)
library(gganimate)
library(RColorBrewer)
library(pals)
library(kableExtra)
library(readxl)
library(lme4)
library(nlme)
library(lmerTest)
library(DHARMa)
library(writexl)
library(lubridate)
library(MASS)
library(nnet)
library(glmmTMB)
library(ggpubr)
library(viridis)

trim <- function (x) gsub("^\\s+|\\s+$", "", x)
firstup <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

reverse_legend_labels <- function(plotly_plot) {
  n_labels <- length(plotly_plot$x$data)
  plotly_plot$x$data[1:n_labels] <- plotly_plot$x$data[n_labels:1]
  plotly_plot
}

str_break <- function(str, n) {
paste(stringi::stri_wrap(str, n, normalise=TRUE,simplify=TRUE),collapse="\n")}

div_palette_gr_fun<-function(x){c(rgb(seq(98,134,length.out = x),seq(166,32,length.out = x),seq(14,65,length.out = x),maxColorValue = 255))}

div_palette_gp_fun<-function(x){c(rgb(seq(98,103,length.out = x),seq(166,37,length.out = x),seq(14,127,length.out = x),maxColorValue = 255))}

div_palette_gbr_fun<-function(x){c(rgb(seq(98,105,length.out = x),seq(166,65,length.out = x),seq(14,44,length.out = x),maxColorValue = 255))}

div_palette_gb_fun<-function(x){c(rgb(seq(98,0,length.out = x),seq(166,115,length.out = x),seq(14,144,length.out = x),maxColorValue = 255))}

qual_palette<-c(rgb(98,166,14,maxColorValue = 255),rgb(103,37,127,maxColorValue = 255),rgb(185,73,23,maxColorValue = 255),rgb(134,32,65,maxColorValue = 255),rgb(0,115,144,maxColorValue = 255),rgb(0,105,57,maxColorValue = 255),rgb(187,243,118,maxColorValue = 255),rgb(199,140,221,maxColorValue = 255),rgb(239,157,122,maxColorValue = 255),rgb(226,135,165,maxColorValue = 255),rgb(106,225,255,maxColorValue = 255),rgb(106,255,188,maxColorValue = 255))

#home-made functions that may be required

#### conversion factors ####
hardwood_m3_per_tonne<-1.43
hardwood_m3_per_hft<-0.03605


setwd("C:/Users/jack.forster/OneDrive - Forest Research/Documents/HomeDrive/157b22_GiB/hwpsc/Report")
```


```{r data load and clean, include=FALSE}

gib_raw<-data.frame(t(read.csv("C:/Users/jack.forster/OneDrive - Forest Research/Documents/HomeDrive/157b22_GiB/R Code and Data/2897344.csv")))


Qu_sub_not_fill_match<-c("X...UserID","UserNo","Name","Email","IP.Address","Unique.ID","Started","Ended","Q1..Please.enter.the.respondent.reference.number.provided.to.you.via.email..6.character.digit.alpha.numeric.reference..e.g..a12b3c..","Q2..How.many.timber.parcels.were.you.responsible.for.selling.buying.from.01.01.2022.to.31.12.2022.in.total.","Q3..Location.of.parcel..County","Q4..Location.of.parcel..Region","Q8..Please.describe.whether.this.was.a.sale.or.purchase.of.a.felled.or.standing.timber.parcel.")#  don't want these to be filled down in Qu_sub

gib_raw <-
  gib_raw %>% mutate(
    Qu_main = trim(paste0(row.names(gib_raw))),
    Qu_sub = trim(paste0(X1)),
    Qu_sub_sub = trim(paste0(gib_raw$X2)),
    Qu_main = ifelse(str_detect(Qu_sub, "Site specific or other factors that alter prices"),"QXX Site specific or other factors that alter prices",Qu_main),
    Qu_sub = ifelse(str_detect(Qu_main, "Are.there.any.hardwood.tree.species.that.were.not"),"Unfilled",Qu_sub),
    Qu_sub = ifelse(Qu_main %in% Qu_sub_not_fill_match, "Unfilled", Qu_sub),
    Qu_main = ifelse(str_detect(Qu_main,"UserID"), "UserID", Qu_main),
    Qu_main = ifelse(substr(Qu_main, 1, 1) == "X", NA, Qu_main),
    Qu_sub = ifelse(Qu_sub == "", NA, Qu_sub)
  ) %>% fill(Qu_main:Qu_sub) %>% 
  mutate(Parameter = paste(Qu_main, Qu_sub, Qu_sub_sub, sep =":")) %>%
  dplyr::select(-c(X1:X2))
row.names(gib_raw)<-NULL # remove row names

gib_raw_user_details <-
  gib_raw %>% filter(Qu_main %in% c("UserID","UserNo","Started","Ended","Q1..Please.enter.the.respondent.reference.number.provided.to.you.via.email..6.character.digit.alpha.numeric.reference..e.g..a12b3c..","Q2..How.many.timber.parcels.were.you.responsible.for.selling.buying.from.01.01.2022.to.31.12.2022.in.total.","Q3..Location.of.parcel..County","Q4..Location.of.parcel..Region","Q5..Overall.parcel.volume..please.answer.using.your.preferred.units...Please.provide.responses.in.either.cubic.metres.or.hoppus.feet.","Q6..Date.of.felling...estimated","Q7..Date.of.sale.purchase","Q8..Please.describe.whether.this.was.a.sale.or.purchase.of.a.felled.or.standing.timber.parcel.")) %>% mutate(Qu_main = ifelse(str_detect(Qu_main,"Q5.."),paste0(Qu_main,":",Qu_sub_sub),Qu_main)) %>%
  pivot_longer(!Qu_main:Parameter) %>%
  dplyr::select(-c(Parameter,Qu_sub,Qu_sub_sub))%>%
  pivot_wider(names_from=Qu_main,values_from = value) %>% dplyr::select(-name) %>%
  dplyr::rename("Unique_GiB_Ref"="Q1..Please.enter.the.respondent.reference.number.provided.to.you.via.email..6.character.digit.alpha.numeric.reference..e.g..a12b3c..","N_Timber_Parcels"="Q2..How.many.timber.parcels.were.you.responsible.for.selling.buying.from.01.01.2022.to.31.12.2022.in.total.","County"="Q3..Location.of.parcel..County","Region"="Q4..Location.of.parcel..Region","Parcel_Volume_m3"="Q5..Overall.parcel.volume..please.answer.using.your.preferred.units...Please.provide.responses.in.either.cubic.metres.or.hoppus.feet.:Q5.1.1. m3","Parcel_Volume_hft"="Q5..Overall.parcel.volume..please.answer.using.your.preferred.units...Please.provide.responses.in.either.cubic.metres.or.hoppus.feet.:Q5.1.2. hft","Date_felled_est"="Q6..Date.of.felling...estimated","Date_sale_purchase_est"="Q7..Date.of.sale.purchase","Cat_Key_Trt"="Q8..Please.describe.whether.this.was.a.sale.or.purchase.of.a.felled.or.standing.timber.parcel.")


gib_raw_timber_details <-
  gib_raw %>% filter(!Qu_main %in% c("UserNo","Name","Email","IP.Address","Unique.ID","Started","Ended","Q1..Please.enter.the.respondent.reference.number.provided.to.you.via.email..6.character.digit.alpha.numeric.reference..e.g..a12b3c..","Q2..How.many.timber.parcels.were.you.responsible.for.selling.buying.from.01.01.2022.to.31.12.2022.in.total.","Q3..Location.of.parcel..County","Q4..Location.of.parcel..Region","Q5..Overall.parcel.volume..please.answer.using.your.preferred.units...Please.provide.responses.in.either.cubic.metres.or.hoppus.feet.","Q6..Date.of.felling...estimated","Q7..Date.of.sale.purchase","Q8..Please.describe.whether.this.was.a.sale.or.purchase.of.a.felled.or.standing.timber.parcel.")) %>%
  pivot_longer(!Qu_main:Parameter) %>% group_by (name) %>% mutate(UserID=value[Qu_main=="UserID"]) %>%ungroup() %>% 
  filter(!Qu_main=="UserID") %>%
  mutate(across(Qu_main:Qu_sub_sub,~gsub("[.]"," ",.x))) %>% mutate(Qu_main=trim(substr(Qu_main,4,nchar(Qu_main))), Qu_sub=ifelse(str_detect(Qu_sub,"Unfilled"),"Unfilled",trim(substr(Qu_sub,7,nchar(Qu_sub)))), Qu_sub_sub=ifelse(str_detect(Qu_sub_sub,"Unfilled"),"Unfilled",trim(substr(Qu_sub_sub,9,nchar(Qu_sub_sub))))) 

gib_raw_numeric_timber_details<- gib_raw_timber_details %>% filter(str_starts(Qu_main,"Timber|Firewood")) %>% dplyr::select(UserID,Qu_main,Qu_sub,Qu_sub_sub,value) %>% group_by(UserID,Qu_main,Qu_sub,Qu_sub_sub) %>%
  summarise(value=sum(as.numeric(value),na.rm=TRUE)) %>%ungroup() %>%
  mutate(Timber_Firewood=ifelse(str_starts(Qu_main,"Timber"),"Timber","Firewood"),Tree_Species_Product=Qu_sub)%>%dplyr::select(UserID,Timber_Firewood,Tree_Species_Product,Qu_sub_sub,value)%>%pivot_wider(names_from=Qu_sub_sub, values_from=value)

gib_raw_character_timber_details<- gib_raw_timber_details %>% filter(str_starts(Qu_main,"Timber|Firewood")==FALSE)%>%filter(str_starts(Qu_main,"Location of timber parcel")==FALSE) %>% dplyr::select(UserID,Qu_main,value) %>% distinct() %>% arrange(desc(value)) %>% group_by(UserID,Qu_main)%>%slice_head(n=1) %>% pivot_wider(names_from=Qu_main, values_from=value)

gib_raw_gps_timber_details<- gib_raw_timber_details %>% filter(str_starts(Qu_main,"Timber|Firewood")==FALSE)%>%filter(str_starts(Qu_main,"Location of timber parcel")) %>% dplyr::select(UserID,Qu_sub_sub,value) %>% distinct() %>% arrange(desc(value)) %>% group_by(UserID,Qu_sub_sub)%>%slice_head(n=1) %>% pivot_wider(names_from=Qu_sub_sub, values_from=value)
  
gib_clean_data<-full_join(full_join(full_join(gib_raw_user_details,gib_raw_character_timber_details),gib_raw_gps_timber_details),gib_raw_numeric_timber_details)

write_xlsx(gib_clean_data,"gib_clean_data.xlsx")
```



```{r aligning units etc, include=FALSE}
gib_clean_data_units_aligned <-
  gib_clean_data %>% mutate(N_Timber_Parcels=as.numeric(N_Timber_Parcels),
    across(Parcel_Volume_m3:Parcel_Volume_hft,
      ~ ifelse(is.na(as.numeric(.)), 0, as.numeric(.))),
    across(`Price (£/m3)`:`Total Volume (m3)`, ~ ifelse(is.na(.), 0, .)),
    Price_Clean_m3 = `Price (£/m3)` + `Price (£/tonne)` / hardwood_m3_per_tonne +
      `Price (£/hft)` / hardwood_m3_per_hft,
    Volume_Clean_m3 = `Volume (m3)` + `Volume (tonnes)` * hardwood_m3_per_tonne +
      `Total Volume (hft)` * hardwood_m3_per_hft + `Total Volume (m3)`,
    Average_Size_Clean_m3 = `Average Log Size (hft)` * hardwood_m3_per_hft +
      `Average Log Size (m3)` + `Average Tree Size (hft)` * hardwood_m3_per_hft +
      `Average Tree Size (m3)`,
    Log_Tree = ifelse(Cat_Key_Trt == "Purchase: Felled", "Log", "Tree"),
    Parcel_Volume_Clean_m3 = Parcel_Volume_m3 + Parcel_Volume_hft * hardwood_m3_per_hft
  )%>%dplyr::select(-c(Parcel_Volume_m3:Parcel_Volume_hft,`Price (£/m3)`:`Total Volume (m3)`))%>%filter(!Volume_Clean_m3==0)%>%mutate(Tree_Species=str_split(Tree_Species_Product," ",simplify=TRUE)[,1],Tree_Species=ifelse(Tree_Species=="Sweet","Sweet Chestnut",Tree_Species),Grade=ifelse(str_detect(str_to_lower(Tree_Species_Product),"biomass"),"Grade C",word(str_extract(Tree_Species_Product, "Grade.*"),1,2,sep=" ")),Grade=ifelse(is.na(Grade),"Mixed/Unknown",Grade),Product=case_when(
    Timber_Firewood=="Firewood"~"Biomass/Firewood",
    str_detect(str_to_lower(Tree_Species_Product),"planking")~"Planking",
    str_detect(str_to_lower(Tree_Species_Product),"biomass")~"Biomass/Firewood",
    str_detect(str_to_lower(Tree_Species_Product),"sawlogs")~"Sawlogs",
    str_detect(str_to_lower(Tree_Species_Product),"beam")~"Beam",
    TRUE~"Mixed/Unknown"
    ))
write_xlsx(gib_clean_data_units_aligned,"gib_clean_data_units_aligned.xlsx")
```




```{r initial plots, include=FALSE}
gg_gib1<-ggplot(gib_clean_data_units_aligned,aes(x=Tree_Species_Product,y=Price_Clean_m3))+
  theme_bw()+
  #facet_wrap(~Log_Tree,scales="free")+
  geom_jitter(aes(colour=Tree_Species_Product),size=3,alpha=0.5,width=0.2)+
  geom_boxplot(colour="black",fill=NA,outlier.shape = NA,width=0.4)+
  labs(x="Product",y=expression(Price~(GBP~m^-3)))+
  theme(axis.text=element_text(size=12),axis.text.x = element_text(size=10,angle=90,hjust=1,vjust=0.5),axis.title=element_text(face="bold",size=14),strip.background=element_rect(fill=NA),strip.text=element_text(size=10))+
  guides(colour="none")


#### define product
model_1<-lmer(Price_Clean_m3~splines::ns(scale(Volume_Clean_m3),df=3)*(Tree_Species+Grade+Cat_Key_Trt+Timber_Firewood)+scale(Parcel_Volume_Clean_m3)+Log_Tree+N_Timber_Parcels+Region+(1|Unique_GiB_Ref),data=gib_clean_data_units_aligned)

gg_gib2<-ggplot(gib_clean_data_units_aligned,aes(x=Average_Size_Clean_m3,y=Price_Clean_m3))+
  theme_bw()+
  facet_wrap(~Log_Tree,scales="free")+
  geom_point(aes(colour=Tree_Species),size=3,alpha=0.7)+
  geom_smooth(aes(colour=Tree_Species,fill=Tree_Species),method="lm",alpha=0.3)+
  labs(x=expression(Price~(GBP~m^-3)),y=expression(Volume~(m^3)))+
  theme(axis.text=element_text(size=12),axis.text.x = element_text(size=10,angle=90,hjust=1,vjust=0.5),axis.title=element_text(face="bold",size=14),strip.background=element_rect(fill=NA),strip.text=element_text(size=10))+
  guides(fill="none")
gg_gib2
```


```{r initial functions analysis, include=FALSE}
tree_sp_func<-list("Ash","Beech","Cherry","Lime","Mixed","Oak","Poplar","Sweet Chestnut","Sycamore")[6][[1]]

tree_pred_func<-list("Log/Tree Size","Sale/Purchase Type","Product","Region")[1][[1]]

tree_additional_func<-list("Sale/Purchase Type","Product","Region")[1][[1]]


gib_clean_data_units_aligned<-read_xlsx("C:/Users/jack.forster/OneDrive - Forest Research/Documents/HomeDrive/157b22_GiB/R Code and Data/gib_clean_data_units_aligned.xlsx")

gib_clean_data_analysis<-gib_clean_data_units_aligned%>%filter(Tree_Species==tree_sp_func) #select relevant tree species

tree_pred_func_orig<-tree_pred_func
tree_pred_func<-dplyr::recode(tree_pred_func,"Sale/Purchase Type"="Cat_Key_Trt")
tree_additional_func<-dplyr::recode(unlist(tree_additional_func),"Sale/Purchase Type"="Cat_Key_Trt")
# recode inputs


if(tree_pred_func == "Log/Tree Size") {
  if(length(tree_additional_func)>1) {tree_additional_func<-paste0("interaction(",paste(tree_additional_func,collapse=","),")")}
 tree_additional_func_group<-paste0("interaction(","Average_Size_Clean_m3",",tree_additional_func",")")
    gg_tree_size<-ggplot(gib_clean_data_analysis,aes_string(x="Average_Size_Clean_m3",y="Price_Clean_m3",colour=tree_additional_func,fill=tree_additional_func,group=tree_additional_func))+
                 theme_bw()+
                  geom_smooth(aes(text=paste0("Best fit line: ",scales::comma(Price_Clean_m3,accuracy=0.01))),method = 'lm')+
                 geom_jitter(aes(text=paste0("Size = ",scales::comma(Average_Size_Clean_m3,accuracy=0.1)," m<sup>3</sup>","\n","Price = ",scales::comma(Price_Clean_m3,accuracy=0.01),"GBP\n",Cat_Key_Trt,"\n",Product,"\n",Region)),
                                size=1.5,alpha=0.7,height=0,width=0.025)+
      labs(x="Average log/tree size (m<sup>3</sup>)",y="Price (GBP)",colour="Grouping\n",fill="Grouping\n",title=paste(tree_sp_func," prices"))+
      scale_colour_viridis(discrete=TRUE)+
      scale_fill_viridis(discrete=TRUE)

    gg_tree_size<-ggplotly(gg_tree_size,tooltip=c("text"))%>%layout(title=list(x=0.5,font=list(size=20)),legend = list(x=1.1,y=0.5,yanchor="middle"),hoverlabel=list(xanchor="left",yanchor="middle"))%>%style(textposition = "left") 
    for(i in 1: length(gg_tree_size$x$layout$shapes)) {gg_tree_size$x$layout$shapes[[i]]$line$width<-0.5}
    gg_tree_size
  
} else {

  if(length(tree_additional_func)>1) {tree_additional_func<-paste0("interaction(",paste(tree_additional_func,collapse=","),")")}
 tree_additional_func_group<-paste0("interaction(",tree_pred_func,",",tree_additional_func,")") 
    gg_tree_size<-ggplot(gib_clean_data_analysis,aes_string(x=tree_pred_func,y="Price_Clean_m3",colour=tree_additional_func,fill=tree_additional_func,group=tree_additional_func_group))+
                 theme_bw()+
                 geom_violin(colour=NA,alpha=0.4,position=position_dodge(width=0.4))+
                 geom_point(aes(text=paste0("Size = ",scales::comma(Average_Size_Clean_m3,accuracy=0.1)," m<sup>3</sup>","\n","Price = ",scales::comma(Price_Clean_m3,accuracy=0.01),"GBP\n",Cat_Key_Trt,"\n",Product,"\n",Region)),position=position_jitterdodge(jitter.width=0.1,dodge.width=0.4),
                                size=1.5,alpha=0.7,height=0,width=0.075)+
      labs(x=paste(tree_pred_func_orig),y="Price (GBP)",colour="Grouping\n",fill="Grouping\n",title=paste(tree_sp_func," prices"))+
      scale_colour_viridis(discrete=TRUE)+
      scale_fill_viridis(discrete=TRUE)

    gg_tree_size<-ggplotly(gg_tree_size,tooltip=c("text"))%>%layout(title=list(x=0.5,font=list(size=20)),legend = list(x=1.1,y=0.5,yanchor="middle"),hoverlabel=list(xanchor="left",yanchor="middle"))%>%style(textposition = "left") 
    for(i in 1: length(gg_tree_size$x$layout$shapes)) {gg_tree_size$x$layout$shapes[[i]]$line$width<-0.5}
    for(i in 1:length(gg_tree_size$x$data))
    {if(length(gg_tree_size$x$data[[i]]$text)>1000) {gg_tree_size$x$data[[i]]$text<-""}}
    for(i in 1:length(gg_tree_size$x$data))
    {if(str_detect(gg_tree_size$x$data[[i]]$name,"[)]")) {gg_tree_size$x$data[[i]]$showlegend<-FALSE}}
    gg_tree_size}
  

#model_1<-lmer(Price_Clean_m3~splines::ns(Average_Size_Clean_m3,df=3)*(Tree_Species+Cat_Key_Trt+Product)+scale(Parcel_Volume_Clean_m3)+scale(Volume_Clean_m3)+scale(N_Timber_Parcels)+Region+(1|Unique_GiB_Ref),data=gib_clean_data_units_aligned)

tree_pred_func<-dplyr::recode(tree_pred_func,"Sale/Purchase Type"="Cat_Key_Trt","Species"="Tree_Species")

tree_pred_func_all<-c("Cat_Key_Trt","Tree_Species","Product","Region")

tree_pred_func_all<-tree_pred_func_all[! tree_pred_func_all %in% tree_pred_func]
  
if(tree_pred_func == "Log/Tree Size") {
  
} else
#emmeans(model_1,rg.limit = 10800,formula(paste0("~", tree_pred_func,"+Average_Size_Clean_m3","|",paste(tree_pred_func_all,collapse="+"))),at=list(Average_Size_Clean_m3=seq(min(gib_clean_data_units_aligned$Average_Size_Clean_m3,na.rm=TRUE),max(gib_clean_data_units_aligned$Average_Size_Clean_m3,na.rm=TRUE),length.out=10)))

```
